### PR TITLE
Fix a bunch of linking issues for locales

### LINKED ISSUE #2006: Certain links fail as a result of locale negotiation
React-router is having a hard time handling some links on https://teach.mofostaging.net/en-US/web-literacy/skills

### PR DESCRIPTION
**Pull request by alanmoo**
Fixes #2006

**Changes proposed in this pull request:**
- Add localization to links for web-literacy skills
- Make badges work
- Add a l10n string that was missing

@pomax can you also take a look over this, specifically `routes.jsx`? I removed the redirects from the one array because they don't seem to specifically be necessary- they get passed as a separate object and redirects work without that line.

### CODE REVIEW

**Comment by alicoding** [comment]
LGTM

File: components/sidebar/topLevelNavItems.jsx [hunk 1]
```diff
@@ -33,7 +33,7 @@ var MENU_ENTRIES = [
         to: '/clubs'
       },
       {
-        name: "Guides & Resources",
+        name: "guides_and_resources",
```
Comment (Pomax) [inline components/sidebar/topLevelNavItems.jsx]: in the interested of dev sense, should these become `locale_id` rather than `name``?

File: pages/badges/badge-single.jsx [hunk 2]
```diff
@@ -16,16 +16,19 @@ var React = require('react'),
...
+  contextTypes: {
+    intl: React.PropTypes.object
+  },
   render: function() {
     var prev = this.props.prev;
     var next = this.props.next;
     return (
       <div className="badge-navigation">
-        <a className="previous" href={prev.url}>
+        <a className="previous" href={"/" + this.context.intl.locale + prev.url}>
```
Comment (Pomax) [inline pages/badges/badge-single.jsx]: Reading this code makes it feels like it would be very sensible to capture this value as a `this.locale`, or better yet, since `locale` doesn't trickle down but is static for an entire site, having a lib that can act as central locale consultation point... that may be out of scope for this PR, but having to get this value out of a `this.context.intl` namespace seems too elaborate

File: components/sidebar/topLevelNavItems.jsx (hunk 1 above)
Comment (alanmoo) [inline components/sidebar/topLevelNavItems.jsx]: This has already been merged in from another PR, it was a random warning that I noticed while writing this patch.

File: pages/badges/badge-single.jsx [hunk 3]
```diff
@@ -16,16 +16,19 @@ var React = require('react'),
...
           <img src={prev.img} />
           <span clasName="label">← {prev.title}</span>
         </a>
-        <a className="next" href={next.url}>
+        <a className="next" href={"/" + this.context.intl.locale + next.url}>
```
Comment (Pomax) [inline pages/badges/badge-single.jsx]: it also feels like this is unnecessarily not-DRY: we can easily write a component `<LocaleLink>` such that we can simply pass in the urls you see in routes.jsx, without having to worry about whether you forgot the local prefix or not. If that is out of scope for this PR: that absolutely should be filed as followup so we're not introducing a new way in which to break the code with a simple typo or forgetting about localization.

File: pages/badges/badges.jsx [hunk 4]
```diff
@@ -155,6 +155,7 @@ var BadgesPage = React.createClass({
   },
 
   generateBadgeList: function() {
+    var that = this;
```
Comment (Pomax) [inline pages/badges/badges.jsx]: Hmm, this should not be necessary. If we need to refer to the instance, then the function later on should love on the React component and passed into the handler as `this.[functionname]`, rather than aliassing 'that' (since React does autorebinding for component functions)

File: pages/badges/badge-single.jsx (hunk 3 above)
Comment (alanmoo) [inline pages/badges/badge-single.jsx]: I see where you're coming from, but that does require remembering to use the appropriate link element, so it's not a foolproof win.

File: pages/web-literacy/MakeLinksFromWebLitSkills.jsx [hunk 5]
```diff
@@ -5,12 +5,12 @@ var ReactRouter = require('react-router');
...
 var convertToRoute = require("../../lib/util").convertToRoute;
 
-var MakeLinksFromWebLitSkills = function(webLitSkills) {
+var MakeLinksFromWebLitSkills = function(webLitSkills, locale) {
   return webLitSkills.map(function(webLitSkill, index) {
     return (
       <span className="comma-separated-links" key={webLitSkill}>
         <Link
-          to={"/web-literacy/" + convertToRoute(webLitSkillsContent[webLitSkill].topic) + "/" + convertToRoute(webLitSkill) + "/"}
+          to={"/" + locale + "/web-literacy/" + convertToRoute(webLitSkillsContent[webLitSkill].topic) + "/" + convertToRoute(webLitSkill) + "/"}
```
Comment (Pomax) [inline pages/web-literacy/MakeLinksFromWebLitSkills.jsx]: This, too, feels like we should make a `<LocalLink>`-like component that takes a regular `to` and then rewrites it internally, putting the locale code in without needing a dev to type it anywhere.

File: pages/web-literacy/Skills.jsx [hunk 6]
```diff
@@ -6,14 +6,18 @@ var makeLinksFromWebLitSkills = require("./MakeLinksFromWebLitSkills.jsx");
...
 var Skills21CPage = React.createClass({
+  contextTypes: {
+    intl: React.PropTypes.object
+  },
   statics: {
     pageTitle: '21st Century Skills',
     pageClassName: 'web-literacy-skills-page'
   },
   generateSkillItem: function(skill) {
+    var that = this;
```
Comment (Pomax) [inline pages/web-literacy/Skills.jsx]: this should not be necessary, whatever ends up using `that` should be a component function, with the `this` binding left to React.

File: pages/web-literacy/WebLiteracyPage.jsx [hunk 7]
```diff
@@ -21,11 +21,11 @@ var Util = require("../../lib/util");
 var convertToRoute = Util.convertToRoute;
 var parseRoute = Util.parseRoute;
 
-function makeLinksFrom21CSkills(skills21C) {
+function makeLinksFrom21CSkills(skills21C, locale) {
   return skills21C.map(function(skill21C, index) {
     return (
       <span key={skill21C} className="comma-separated-links">
-        <a href={"/web-literacy/skills/#" + categories[skill21C].toLowerCase()}>
+        <a href={"/" + locale + "/web-literacy/skills/#" + categories[skill21C].toLowerCase()}>
```
Comment (Pomax) [inline pages/web-literacy/WebLiteracyPage.jsx]: see previous note on hardening code against fallible human tendencies =)

File: pages/badges/badges.jsx (hunk 4 above)
Comment (alanmoo) [inline pages/badges/badges.jsx]: Even considering the map below? (line 174)

File: pages/web-literacy/WebLiteracyPage.jsx [hunk 8]
```diff
@@ -184,6 +187,7 @@ var WebLitPage = React.createClass({
     }.bind(this));
   },
   renderTopics: function() {
+    var that = this;
```
Comment (Pomax) [inline pages/web-literacy/WebLiteracyPage.jsx]: see previous notes on React autobinding `this` for component functions

**Comment by Pomax** [comment]
Hmm, I can't seem to run this PR. If I check it out, run `npm i`, then `npm start`, and try `http://localhost:8008` in any browser, both plain and private browsing mode, I get a 307 chain that resolves some 20-odd times and then gives up

File: components/sidebar/topLevelNavItems.jsx (hunk 1 above)
Comment (Pomax) [inline components/sidebar/topLevelNavItems.jsx]: Yeah, I don't think I was on that PR, hence the comment now, really =/

File: pages/badges/badge-single.jsx (hunk 3 above)
Comment (Pomax) [inline pages/badges/badge-single.jsx]: it makes it very easy to check files for use of raw `<a>` though, which is easily automated.

File: pages/badges/badges.jsx (hunk 4 above)
Comment (Pomax) [inline pages/badges/badges.jsx]: yeah, at this point it means that map function should be refactor out of the current code into its own component function instead.

**Comment by Pomax** [comment]
This looks good on mac - I'll file the windows problems a separate issue.

**Comment by alanmoo** [comment]
Merging this in so staging can be un-broken, but filing follow up tickets for some linkage/intl context cleanups.
